use std::fs;
use std::io::Write;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::input::Input;

const CURRENT_VERSION: u32 = 1;

#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    #[error("could not read or write the config: {0}")]
    Io(#[from] std::io::Error),
    #[error("the config is not valid: {0}")]
    Parse(#[from] toml::de::Error),
    #[error("could not serialize the config: {0}")]
    Serialize(#[from] toml::ser::Error),
    #[error("the config is version {found}, this kvmux understands version {CURRENT_VERSION}")]
    UnsupportedVersion { found: u32 },
}

/// The USB device whose connection triggers the switch.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UsbId {
    pub vendor_id: u16,
    pub product_id: u16,
    /// Tells identical devices apart when the device reports one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,
    /// Name shown in the UI. Not used for matching.
    pub label: String,
}

/// What to do for one monitor.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MonitorRule {
    /// EDID based id: manufacturer, product code and serial.
    pub id: String,
    /// Name shown in the UI. Not used for matching.
    pub label: String,
    pub on_connect: Input,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub on_disconnect: Option<Input>,
}

/// Generated by the settings window. Not meant to be edited by hand.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    pub version: u32,
    #[serde(default)]
    pub autostart: bool,
    #[serde(default = "default_true")]
    pub auto_update: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trigger: Option<UsbId>,
    #[serde(default, rename = "monitor", skip_serializing_if = "Vec::is_empty")]
    pub monitors: Vec<MonitorRule>,
}

fn default_true() -> bool {
    true
}

impl Default for Config {
    fn default() -> Self {
        Self {
            version: CURRENT_VERSION,
            autostart: false,
            auto_update: true,
            trigger: None,
            monitors: Vec::new(),
        }
    }
}

impl Config {
    pub fn from_toml(text: &str) -> Result<Self, ConfigError> {
        let config: Config = toml::from_str(text)?;
        if config.version != CURRENT_VERSION {
            return Err(ConfigError::UnsupportedVersion {
                found: config.version,
            });
        }
        Ok(config)
    }

    pub fn to_toml(&self) -> Result<String, ConfigError> {
        Ok(toml::to_string_pretty(self)?)
    }

    /// A missing file is the default config, not an error.
    pub fn load(path: &Path) -> Result<Self, ConfigError> {
        match fs::read_to_string(path) {
            Ok(text) => Self::from_toml(&text),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(Self::default()),
            Err(error) => Err(error.into()),
        }
    }

    /// Writes to a temporary file next to `path`, then renames it over `path`,
    /// so a reader never sees a half written config.
    pub fn save(&self, path: &Path) -> Result<(), ConfigError> {
        let text = self.to_toml()?;
        let directory = path.parent().unwrap_or_else(|| Path::new("."));
        fs::create_dir_all(directory)?;
        let mut file = tempfile_in(directory)?;
        file.write_all(text.as_bytes())?;
        file.sync_all()?;
        let (_, temp_path) = file.into_parts();
        fs::rename(&temp_path, path)?;
        Ok(())
    }
}

/// A private temporary file in `directory`, readable only by the user on Unix.
fn tempfile_in(directory: &Path) -> std::io::Result<TempFile> {
    let path = directory.join(format!(".config.{}.tmp", std::process::id()));
    let mut options = fs::OpenOptions::new();
    options.write(true).create(true).truncate(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let file = options.open(&path)?;
    Ok(TempFile { file, path })
}

struct TempFile {
    file: fs::File,
    path: std::path::PathBuf,
}

impl TempFile {
    fn write_all(&mut self, bytes: &[u8]) -> std::io::Result<()> {
        self.file.write_all(bytes)
    }

    fn sync_all(&self) -> std::io::Result<()> {
        self.file.sync_all()
    }

    fn into_parts(self) -> (fs::File, std::path::PathBuf) {
        (self.file, self.path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Config {
        Config {
            trigger: Some(UsbId {
                vendor_id: 0x046d,
                product_id: 0xc52b,
                serial: None,
                label: "Logitech Receiver".into(),
            }),
            monitors: vec![
                MonitorRule {
                    id: "DEL:41C3:ABC123".into(),
                    label: "Dell U2723QE".into(),
                    on_connect: Input::DisplayPort2,
                    on_disconnect: Some(Input::Hdmi1),
                },
                MonitorRule {
                    id: "LEN:6543:XYZ".into(),
                    label: "Lenovo".into(),
                    on_connect: Input::Raw(0x1b),
                    on_disconnect: None,
                },
            ],
            ..Config::default()
        }
    }

    #[test]
    fn round_trips_through_toml() {
        let config = sample();
        let text = config.to_toml().expect("serialize");
        assert_eq!(Config::from_toml(&text).expect("parse"), config);
    }

    #[test]
    fn missing_file_is_the_default() {
        let dir = tempfile::tempdir().expect("tempdir");
        let config = Config::load(&dir.path().join("config.toml")).expect("load");
        assert_eq!(config, Config::default());
    }

    #[test]
    fn save_then_load() {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("nested").join("config.toml");
        sample().save(&path).expect("save");
        assert_eq!(Config::load(&path).expect("load"), sample());
    }

    #[cfg(unix)]
    #[test]
    fn saved_file_is_private() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("config.toml");
        sample().save(&path).expect("save");
        let mode = fs::metadata(&path).expect("metadata").permissions().mode();
        assert_eq!(mode & 0o777, 0o600);
    }

    #[test]
    fn rejects_unknown_fields() {
        let text = "version = 1\nsurprise = true\n";
        assert!(matches!(
            Config::from_toml(text),
            Err(ConfigError::Parse(_))
        ));
    }

    #[test]
    fn rejects_other_versions() {
        let text = "version = 2\n";
        assert!(matches!(
            Config::from_toml(text),
            Err(ConfigError::UnsupportedVersion { found: 2 })
        ));
    }

    #[test]
    fn rejects_bad_inputs() {
        let text =
            "version = 1\n[[monitor]]\nid = \"a\"\nlabel = \"a\"\non_connect = \"thunderbolt\"\n";
        assert!(matches!(
            Config::from_toml(text),
            Err(ConfigError::Parse(_))
        ));
    }
}
